version: '3'
services:
  neo4j:
    image: neo4j:4.4.6
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=256MB
      - NEO4J_dbms.memory.heap.initial_size=256MB
      - NEO4J_dbms_memory_heap_max__size=256MB